language: python
python:
  - "3.5.2"
  
sudo: false
cache: pip3
  
install:
  - pip install -r requirements.txt

script:
- pytest -v --cov app --cov-report term-missing
- coverage
- coveralls
- coverage report

after_success:
  - coveralls
