language: python

python:
  - "3.6"

sudo: false
cache: pip3

install:
  - pip install -r requirements.txt

script:
  - py.test --cov-config .coveragerc --cov=Api
- coverage
- coveralls
- coverage report

after_success:
  - coveralls
