language: python
python:
- '3.5.2'
sudo: false
cache: pip3
install:
- pip install -r requirements.txt
script:
 - py.test --cov-config .coveragerc --cov=api
- coverage
- coveralls
- coverage report
after_success:
- coveralls
