language: python
python:
  - "3.6"
  
install:
  - pip install -r requirements.txt

script:
- py.test --cov-config .coveragerc --cov=SendIT-Api
- coverage
- coveralls
- coverage report
  
after_success:
  - coveralls
