language: python
python:
  - "3.6"
  
install:
  - pip install -r requirements.txt

script:
- py.test --cov=JamesMudidi / SendIT-Api / tests/
- coverage
- coveralls
- coverage report
  
after_success:
  - coveralls
