language: python
python:
  - "3.6"
  
sudo: false
cache: pip3
  
install:
  - pip install -r requirements.txt

script:
  - pytest
  - coverage
  - coverage3 report
  - coveralls 
  
after_success:
  - coveralls
